#!/bin/sh
# =============================================================================
# Attach fixture images to the seeded posts and set coherent editorial flags, so
# the local stack renders a realistic front page instead of empty image frames.
#
# Run: ./sync.sh && docker compose run --rm wpcli /var/www/html/.pgds-scripts/seed-media.sh
#
# The images are abstract compositions generated by tools/seed-images.mjs. They are
# layout fixtures, not editorial assets.
# =============================================================================
set -e

WP="wp --path=/var/www/html --allow-root"
IMG_DIR="/var/www/html/.pgds-tools/seed-images"

if [ ! -d "$IMG_DIR" ]; then
  echo "ERROR: $IMG_DIR is missing. Run 'node tools/seed-images.mjs tools/seed-images' then ./sync.sh." >&2
  exit 1
fi

echo "==> Deleting the default WordPress sample content..."
# 'Hello world!' and 'Sample Page' otherwise win the front-page lead slot on recency
# and show 'UNCATEGORIZED' in the most prominent position on the site.
for slug in hello-world sample-page; do
  id=$($WP post list --post_type=post,page --name="$slug" --field=ID 2>/dev/null | head -1)
  if [ -n "$id" ]; then
    $WP post delete "$id" --force
    echo "    deleted: $slug"
  fi
done

echo "==> Attaching a featured image to every post that lacks one..."
i=1
for id in $($WP post list --post_type=post --post_status=publish --field=ID --orderby=date --order=DESC); do
  if [ -n "$($WP post meta get "$id" _thumbnail_id 2>/dev/null)" ]; then
    continue
  fi
  # Cycle through the 24 fixtures so adjacent cards do not repeat an image.
  n=$(printf '%02d' $(( (i - 1) % 24 + 1 )))
  file="$IMG_DIR/pgds-seed-$n.png"
  [ -f "$file" ] || continue

  title=$($WP post get "$id" --field=post_title)
  # The alt text carries the post title: these frames are content images inside a
  # link, so an empty alt would leave the link unnamed for screen readers.
  att=$($WP media import "$file" --post_id="$id" --featured_image --title="$title" --alt="$title" --porcelain 2>/dev/null) || true
  if [ -n "$att" ]; then
    echo "    post $id <- pgds-seed-$n.png"
  fi
  i=$((i + 1))
done

echo "==> Setting coherent editorial flags..."
# Curated slots must not collide: a post used as the lead is consumed by the dedup
# pass (proposal §4.4), so flagging the same post as the photo story left the panel
# empty. Rank 1 is the lead, ranks 2-4 the secondary cards, and the photo story is
# a DIFFERENT post again.
$WP post meta delete $($WP post list --post_type=post --field=ID) _pgds_is_featured 2>/dev/null || true
$WP post meta delete $($WP post list --post_type=post --field=ID) _pgds_feature_rank 2>/dev/null || true
$WP post meta delete $($WP post list --post_type=post --field=ID) _pgds_photo_story 2>/dev/null || true

rank=1
for id in $($WP post list --post_type=post --post_status=publish --field=ID --orderby=date --order=DESC --posts_per_page=4); do
  $WP post meta update "$id" _pgds_is_featured 1 >/dev/null
  $WP post meta update "$id" _pgds_feature_rank "$rank" >/dev/null
  echo "    featured rank $rank -> post $id"
  rank=$((rank + 1))
done

# Photo story: the 5th and 6th newest, i.e. posts NOT already claimed above.
for id in $($WP post list --post_type=post --post_status=publish --field=ID --orderby=date --order=DESC --posts_per_page=6 | tail -2); do
  $WP post meta update "$id" _pgds_photo_story 1 >/dev/null
  echo "    photo story -> post $id"
done

echo "==> Seeding the perpetual-calendar note so the widget shows real lunar data..."
lunar=$($WP post list --post_type=pgds_lunar_note --field=ID --posts_per_page=1)
if [ -z "$lunar" ]; then
  lunar=$($WP post create --post_type=pgds_lunar_note --post_status=publish \
    --post_title="Lịch $(date +%d/%m/%Y)" --porcelain)
fi
$WP post meta update "$lunar" _pgds_lunar_day "16" >/dev/null
$WP post meta update "$lunar" _pgds_lunar_sub "Tháng 7 Bính Ngọ" >/dev/null
$WP post meta update "$lunar" _pgds_menh "Sơn đầu hỏa" >/dev/null
$WP post meta update "$lunar" _pgds_gio "Dần (3h-5h), Thìn (7h-9h), Tỵ (9h-11h)" >/dev/null

echo "==> Seeding the remaining teachings so the sidebar block is full..."
for t in "Nhân quả và cách sống thiện lành mỗi ngày" \
         "Tứ Vô Lượng Tâm: Từ - Bi - Hỷ - Xả trong đời sống" \
         "Giữ tâm bình thản trước mọi biến động cuộc đời"; do
  if [ -z "$($WP post list --post_type=pgds_teaching --title="$t" --field=ID)" ]; then
    $WP post create --post_type=pgds_teaching --post_status=publish --post_title="$t" >/dev/null
  fi
done

echo "==> Flushing caches..."
$WP cache flush >/dev/null 2>&1 || true

echo ""
echo "==> Media seed complete."
