<?php
/**
 * Asset enqueue.
 *
 * Reads assets/dist/manifest.json to get the filename with content hash
 * (generated by build.mjs). The filename changes when content changes, so it's
 * safe to pair with `Cache-Control: immutable` (proposal §5.5).
 *
 * @package pgds
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Read the build manifest (cached for the duration of one request).
 *
 * @return array<string,string>
 */
function pgds_manifest() {
	static $manifest = null;
	if ( null !== $manifest ) {
		return $manifest;
	}
	$path = PGDS_DIR . '/assets/dist/manifest.json';
	if ( is_readable( $path ) ) {
		$decoded  = json_decode( (string) file_get_contents( $path ), true );
		$manifest = is_array( $decoded ) ? $decoded : array();
	} else {
		$manifest = array();
	}
	return $manifest;
}

/**
 * URL of a built asset by logical name (e.g. 'main.css').
 *
 * @param string $logical Logical name in the manifest.
 * @return string|null
 */
function pgds_asset_url( $logical ) {
	$m = pgds_manifest();
	if ( empty( $m[ $logical ] ) ) {
		return null;
	}
	return PGDS_URI . '/assets/dist/' . $m[ $logical ];
}

/**
 * Enqueue CSS + JS + preload font.
 */
function pgds_enqueue_assets() {
	$css = pgds_asset_url( 'main.css' );
	$js  = pgds_asset_url( 'app.js' );

	if ( $css ) {
		// Version = null since the filename is already hashed -> avoid double cache-busting.
		wp_enqueue_style( 'pgds-main', $css, array(), null );
	}

	if ( $js ) {
		wp_enqueue_script( 'pgds-app', $js, array(), null, true );
		// Pass runtime config to JS (e.g. nonce later on).
		wp_localize_script(
			'pgds-app',
			'PGDS',
			array(
				'restUrl' => esc_url_raw( rest_url() ),
				'ytHost'  => 'https://www.youtube-nocookie.com',
			)
		);
	}

	// Comments: only load on a single post/page with comments open.
	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}
add_action( 'wp_enqueue_scripts', 'pgds_enqueue_assets' );

/**
 * Preload 2 critical fonts + preconnect (self-hosted, so it's same-origin only).
 * Font files live in assets/fonts/. If a file is missing, the browser will just skip the preload.
 */
function pgds_preload_fonts() {
	$fonts = array(
		'/assets/fonts/be-vietnam-pro-400.woff2',
		'/assets/fonts/fraunces-700.woff2',
	);
	foreach ( $fonts as $f ) {
		$abs = PGDS_DIR . $f;
		if ( is_readable( $abs ) ) {
			printf(
				'<link rel="preload" href="%s" as="font" type="font/woff2" crossorigin>' . "\n",
				esc_url( PGDS_URI . $f )
			);
		}
	}
}
add_action( 'wp_head', 'pgds_preload_fonts', 1 );

/**
 * Add defer to the theme's script tag (JS doesn't block render).
 *
 * @param string $tag    The tag.
 * @param string $handle Handle.
 * @return string
 */
function pgds_script_defer( $tag, $handle ) {
	if ( 'pgds-app' === $handle && false === strpos( $tag, 'defer' ) ) {
		$tag = str_replace( ' src', ' defer src', $tag );
	}
	return $tag;
}
add_filter( 'script_loader_tag', 'pgds_script_defer', 10, 2 );

/**
 * Remove jQuery on the front end (theme doesn't use it). Still kept in admin.
 */
function pgds_dequeue_jquery() {
	if ( ! is_admin() ) {
		// Only remove if no plugin depends on it (safe: only de-register when there's no dependency).
		// To stay safe with plugins, only disable migrate.
		wp_deregister_script( 'jquery-migrate' );
	}
}
add_action( 'wp_enqueue_scripts', 'pgds_dequeue_jquery', 100 );
